/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sikuli_script_LinuxUtil */

#ifndef _Included_org_sikuli_script_LinuxUtil
#define _Included_org_sikuli_script_LinuxUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_sikuli_script_LinuxUtil
 * Method:    getX11FocusedWindow
 * Signature: ()Lorg/sikuli/script/Window;
 */
JNIEXPORT jobject JNICALL Java_org_sikuli_script_LinuxUtil_getX11FocusedWindow
  (JNIEnv *, jclass);

/*
 * Class:     org_sikuli_script_LinuxUtil
 * Method:    getX11Window
 * Signature: (Ljava/lang/String;)Lorg/sikuli/script/Window;
 */
JNIEXPORT jobject JNICALL Java_org_sikuli_script_LinuxUtil_getX11Window__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_sikuli_script_LinuxUtil
 * Method:    getX11Window
 * Signature: (J)Lorg/sikuli/script/Window;
 */
JNIEXPORT jobject JNICALL Java_org_sikuli_script_LinuxUtil_getX11Window__J
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
