/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sikuli_script_LinuxUtil */

#ifndef _Included_org_sikuli_script_LinuxUtil
#define _Included_org_sikuli_script_LinuxUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_sikuli_script_LinuxUtil
 * Method:    getX11FocusedWindow
 * Signature: ()Lorg/sikuli/script/Window;
 */
JNIEXPORT jobject JNICALL Java_org_sikuli_script_LinuxUtil_getX11FocusedWindow
  (JNIEnv *, jclass);

/*
 * Class:     org_sikuli_script_LinuxUtil
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_sikuli_script_LinuxUtil_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
